=== MihailBelyuk/food-delivery-xml/src/fooddelivery.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="food-delivery" type="food-deliveryType"/>
    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element type="xs:string" name="city"/>
            <xs:element type="xs:string" name="district"/>
            <xs:element type="xs:string" name="street"/>
            <xs:element type="xs:string" name="house"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="nameType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="first"/>
                <xs:attribute type="xs:string" name="last"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="carType">
        <xs:sequence>
            <xs:element name="car-brand" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="directorType">
        <xs:sequence>
            <xs:element type="nameType" name="name"/>
            <xs:element type="xs:date" name="date-of-birth">
            </xs:element>
            <xs:element type="xs:string" name="id"/>
            <xs:element type="carType" name="car"/>
        </xs:sequence>
    </xs:complexType>
      <xs:complexType name="ingredient-listType">
        <xs:sequence>
            <xs:element type="xs:string" name="ingredient" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="dishType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:integer" name="prepare-minutes"/>
            <xs:element type="xs:boolean" name="spicy"/>
            <xs:element type="xs:decimal" name="price"/>
            <xs:element type="ingredient-listType" name="ingredient-list"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="dish-listType">
        <xs:sequence>
            <xs:element type="dishType" name="dish" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="restaurantType">
        <xs:sequence>
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="KFC"/>
                        <xs:enumeration value="Burger King"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="dish-listType" name="dish-list"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="restaurant-listType">
        <xs:sequence>
            <xs:element type="restaurantType" name="restaurant" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="clientType">
        <xs:sequence>
            <xs:element type="nameType" name="name"/>
            <xs:element type="xs:dateTime" name="date-of-birth"/>
            <xs:element type="xs:long" name="id"/>
            <xs:element type="carType" name="car"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="orderType">
        <xs:sequence>
            <xs:element type="restaurantType" name="restaurant" nillable="true"/>
            <xs:element type="courierType" name="courier" nillable="true"/>
            <xs:element type="clientType" name="client" nillable="true"/>
            <xs:element type="xs:string" name="payment" nillable="true"/>
            <xs:element type="xs:dateTime" name="creation-time" nillable="true"/>
            <xs:element type="dish-listType" name="dish-list" nillable="true"/>
            <xs:element type="xs:string" name="drink-list" nillable="true"/>
            <xs:element type="xs:nonNegativeInteger" name="delivery-distance" nillable="true"/>
            <xs:element type="xs:nonNegativeInteger" name="distance" nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="order-listType">
        <xs:sequence>
            <xs:element type="orderType" name="order"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="courierType">
        <xs:sequence>
            <xs:element type="nameType" name="name"/>
            <xs:element type="xs:date" name="date-of-birth"/>
            <xs:element type="xs:long" name="id"/>
            <xs:element type="carType" name="car"/>
            <xs:element type="xs:string" name="courier-type"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="courier-listType">
        <xs:sequence>
            <xs:element type="courierType" name="courier" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="food-deliveryType">
        <xs:sequence>
            <xs:element type="addressType" name="address"/>
            <xs:element type="directorType" name="director"/>
            <xs:element type="restaurant-listType" name="restaurant-list"/>
            <xs:element type="order-listType" name="order-list"/>
            <xs:element type="courier-listType" name="courier-list"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== MihailBelyuk/food-delivery-xml/src/main/resources/fooddelivery.xml
<?xml version="1.0" encoding="UTF-8"?>

<food-delivery xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="fooddelivery.xsd">
    <address>
        <city>Minsk</city>
        <street>Lenina str.</street>
        <house>5</house>
    </address>
    <director first-name="John" last-name="Wick">
        <date-of-birth>1965-02-01</date-of-birth>
        <id>123456</id>
        <car>
            <car-brand>Audi</car-brand>
        </car>
    </director>
    <restaurant-list>
        <restaurant>
            <name>KFC</name>
            <dish-list>
                <dish>
                    <name>Hot wings</name>
                    <prepare-minutes>10</prepare-minutes>
                    <spicy>true</spicy>
                    <price>7.00</price>
                    <ingredient-list>
                        <ingredient>chicken wings</ingredient>
                        <ingredient>salt</ingredient>
                        <ingredient>oil</ingredient>
                        <ingredient>chilli</ingredient>
                    </ingredient-list>
                </dish>
                <dish>
                    <name>Nuggets</name>
                    <prepare-minutes>12</prepare-minutes>
                    <spicy>false</spicy>
                    <price>10.00</price>
                    <ingredient-list>
                        <ingredient>chicken meat</ingredient>
                        <ingredient>salt</ingredient>
                        <ingredient>oil</ingredient>
                    </ingredient-list>
                </dish>
            </dish-list>
        </restaurant>
        <restaurant>
            <name>Burger King</name>
            <dish-list>
                <dish>
                    <name>Whopper</name>
                    <prepare-minutes>6</prepare-minutes>
                    <spicy>false</spicy>
                    <price>6.00</price>
                    <ingredient-list>
                        <ingredient>bun</ingredient>
                        <ingredient>beef</ingredient>
                        <ingredient>cheese</ingredient>
                        <ingredient>ketchup</ingredient>
                    </ingredient-list>
                </dish>
                <dish>
                    <name>Big king</name>
                    <prepare-minutes>8</prepare-minutes>
                    <spicy>false</spicy>
                    <price>15.00</price>
                    <ingredient-list>
                        <ingredient>bun</ingredient>
                        <ingredient>beef</ingredient>
                        <ingredient>cheese</ingredient>
                        <ingredient>ketchup</ingredient>
                        <ingredient>salt</ingredient>
                    </ingredient-list>
                </dish>
            </dish-list>
        </restaurant>
    </restaurant-list>
    <order-list>
        <order>
            <restaurant xsi:nil="true"/>
            <courier xsi:nil="true"/>
            <client xsi:nil="true"/>
            <payment xsi:nil="true"/>
            <creation-time xsi:nil="true"/>
            <dish-list xsi:nil="true"/>
            <drink-list xsi:nil="true"/>
            <delivery-distance xsi:nil="true"/>
            <distance xsi:nil="true"/>
        </order>
    </order-list>
    <courier-list>
        <courier first-name="Vasiliy" last-name="Vasiliev">
            <date-of-birth>1990-01-12</date-of-birth>
            <id>28146</id>
            <car>
                <car-brand>WV</car-brand>
            </car>
            <delivery-type>on_foot</delivery-type>
        </courier>
        <courier first-name="Petr" last-name="Petrov">
            <date-of-birth>1999-03-15</date-of-birth>
            <id>123698</id>
            <car>
                <car-brand>Porsche</car-brand>
            </car>
            <delivery-type>car</delivery-type>
        </courier>
        <courier first-name="Ivan" last-name="Ivanov">

            <date-of-birth>1998-03-03</date-of-birth>
            <id>2896586</id>
            <car>
                <car-brand>Porsche</car-brand>
            </car>
            <delivery-type>bicycle</delivery-type>
        </courier>
    </courier-list>
</food-delivery>
